version: "2.0"

services:

  eiti-crud:
    build: .
    container_name: eiti-docker
    ports:
      - 8081:8088
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-docker:3306/db_eiti?useSSL=false
    links:
      - mysql
    networks:
      - eiti-net

  mysql:
    image: mysql:5.6
    container_name: mysql-docker
    expose:
            - "3306"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db_eiti
    networks:
      - eiti-net

networks:
  eiti-net:
    driver: bridge